### ISSUE TITLE
Alarms trigger every second, spamming the chat and on-screen notifications

### ISSUE THREAD

**Issue by LeeMoriya** [KangasZ/EurekaHelper#6]
Only just started doing this. I have an alarm set to remind me 5 minutes before Fog appears in Pagos.

When it triggers, it now pops up every single second, giving me a new notification every time. Even when I deleted the alarm and disable the plugin it continues to trigger!

![image](https://github.com/user-attachments/assets/9238dec8-311f-4cde-963c-631430d027ec)

**Comment by LeeMoriya** [comment]
`2024-12-31 01:17:55.897 +00:00 [ERR] Exception during raise of Void <InvokeSafely>b__0()
System.ArgumentException: Valid chat sfx values are 1 through 16.
   at FFXIVClientStructs.FFXIV.Client.UI.UIGlobals.PlayChatSoundEffect(UInt32 effectId) in /_/FFXIVClientStructs/FFXIV/Client/UI/UIGlobals.cs:line 50
   at EurekaHelper.System.AlarmManager.OnUpdate(IFramework framework) in /work/repo/EurekaHelper/System/AlarmManager.cs:line 52
   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act) in C:\goatsoft\companysecrets\dalamud\\Utility\EventHandlerExtensions.cs:line 124
`

**Comment by KangasZ** [comment]
Appreciate this report, I'll look into it immediately and get a patch out asap

**Comment by LeeMoriya** [comment]
Thank you! Gotta be my all time favourite plugin, thank you for making it

**Comment by KangasZ** [comment]
This seem to have been missed in the migration from the prior version of the config to the new. If you could please attempt to update the alarm then save it with an updated sound effect value, it may resolve the issue while I can patch the code for a long term fix

**Comment by KangasZ** [comment]
An update to resolve this issue has been pushed out for the plugin team to review. Thank you for bringing this to my attention.

**Comment by LeeMoriya** [comment]
Thank you for taking a look at this so quickly!
